---
# tasks file for deluge-docker
- name: create group {{deluge_group}}
  group:
    name: "{{deluge_group}}"
    gid: "{{deluge_gid}}"
    system: true
    state: present

- name: create user {{deluge_user}}
  user:
    name: "{{deluge_user}}"
    uid: "{{deluge_uid}}"
    system: true
    group: "{{deluge_group}}"
    expires: -1
    home: "{{deluge_torrent_path}}"
    shell: "/bin/false"
    create_home: true
    state: present
    
- name: create dirs tmp complets seed archives
  file:
    name: "{{deluge_torrent_path}}/{{item}}"
    state: directory
    owner: "{{deluge_uid}}"
    group: "{{deluge_group}}"
    mode: 0775
  loop: "{{deluge_sub_paths}}"
  when: deluge_sub_paths is defined

- name: create deluge docker dir
  file:
    name: "{{ docker_deluge_dir }}"
    state: directory
    owner: "{{docker_user}}"
    group: "{{docker_group}}"
    mode: 0775
- name: copy docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{docker_deluge_dir}}/docker-compose.yml"
    owner: "{{docker_user}}"
    group: "{{docker_group}}"
    backup: true
    mode: 0664
  notify: 
    - docker down deluge
    - docker up deluge

- name: create deluge config dir
  file:
    name: "{{docker_deluge_config}}"
    state: directory
    owner: "{{deluge_uid}}"
    group: "{{deluge_group}}"
    mode: 0775

- name: docker pull
  community.docker.docker_compose_v2:
    project_src: "{{ docker_deluge_dir }}"
    pull: always
