---
# tasks file for deluge-docker
- import_tasks: core.yml
- import_tasks: plugins.yml
  notify:
    - Docker down deluge
    - Docker up deluge

- name: Copy docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: '{{ docker_deluge_dir }}/docker-compose.yml'
    owner: '{{ docker_deluge_docker_user }}'
    group: '{{ docker_deluge_docker_group }}'
    backup: true
    mode: '0664'
  notify:
    - Docker down deluge
    - Docker up deluge

- name: Docker pull
  community.docker.docker_compose_v2:
    project_src: '{{ docker_deluge_dir }}'
