---
# handlers file for deluge-docker
- name: Docker down deluge
  community.docker.docker_compose_v2:
    project_src: '{{ docker_deluge_dir }}'
    state: absent
  when: docker_deluge_start

- name: Docker up deluge
  community.docker.docker_compose_v2:
    project_src: '{{ docker_deluge_dir }}'
    state: present
  when: docker_deluge_start
